server:
  port: 8081

spring:
  application:
    name: inventory

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
