server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://postgres-user:5432/user_service}
    username: ${USER_DB_USER:user_service_user}
    password: ${USER_DB_PASS:user_service_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8761/eureka/}
