# Type    Database        User            Address         Method
# Conexiones locales
local   all             all                             trust
host    all             all             127.0.0.1/32    trust
host    all             all             ::1/128         trust
# Conexiones de red (acceso normal a base de datos)
host    all             all             0.0.0.0/0       trust
# Replicación (necesario para el nodo réplica)
local   replication     all                             trust
host    replication     all             127.0.0.1/32    trust
host    replication     all             0.0.0.0/0       trust
