package com.economato.inventory.domain.model.notification;

public enum NotificationType {
    WEEKLY_PLAN_CREATED,
    WEEKLY_PLAN_ACTIVATED,
    WEEKLY_PLAN_SLOT_CONFIRMED,
    WEEKLY_PLAN_DAY_CONFIRMED,
    WEEKLY_PLAN_COMPLETED,
    WEEKLY_PLAN_CANCELLED,
    WEEKLY_PLAN_AUTO_CLOSED,
    FOOD_CRISIS_ACTIVATED,
    FOOD_CRISIS_LIFTED,
    STOCK_PREDICTION_TRIGGERED,
    INCIDENT_CREATED,
    INCIDENT_OPENED,
    INCIDENT_CLOSED,
    INCIDENT_CHAT_MESSAGE,
    DRAFT_SUBMITTED,
    DRAFT_APPROVED,
    DRAFT_REJECTED,
    DRAFT_RESUBMITTED,
    MANUAL
}
