package com.economato.inventory.infrastructure.adapter.in.web;

import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.web.servlet.MockMvc;

import com.economato.inventory.infrastructure.adapter.out.messaging.kafka.producer.AuditEventProducer;
import com.economato.inventory.infrastructure.adapter.out.persistence.repository.ProductRepository;
import com.economato.inventory.application.usecase.CustomUserDetailsService;
import com.economato.inventory.infrastructure.DatabaseCleaner;
import com.economato.inventory.application.dto.request.LoginRequestDTO;
import com.economato.inventory.application.dto.response.LoginResponseDTO;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
public abstract class BaseIntegrationTest {

    @MockitoBean
    protected AuditEventProducer auditEventProducer;

    @BeforeAll
    static void configureSecurityContextPropagation() {
        SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);
    }

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper objectMapper;

    @Autowired
    protected EntityManager entityManager;

    @Autowired
    private DatabaseCleaner databaseCleaner;

    @Autowired
    protected CustomUserDetailsService customUserDetailsService;

    /**
     * H2 does not support FOR NO KEY UPDATE generated by @Lock(PESSIMISTIC_WRITE).
     * This spy stubs findByIdForUpdate to delegate to the lock-free findById so
     * every integration test running against H2 works without profile branching
     * in production code.
     */
    @MockitoSpyBean
    protected ProductRepository productRepository;

    @BeforeEach
    void clearUserDetailsCache() {
        customUserDetailsService.clearCache();
        // Stub the pessimistic lock query so H2 doesn't reject it.
        Mockito.doAnswer(inv -> productRepository.findById(inv.getArgument(0)))
                .when(productRepository).findByIdForUpdate(Mockito.any());
    }

    protected String asJsonString(Object obj) {
        try {
            String json = objectMapper.writeValueAsString(obj);
            if (json == null || json.isBlank()) {
                throw new RuntimeException("El JSON generado está vacío");
            }
            return json;
        } catch (Exception e) {
            throw new RuntimeException("Error al serializar objeto a JSON", e);
        }
    }

    protected void clearDatabase() {
        databaseCleaner.clear();
    }

    protected String login(String username, String password) throws Exception {
        LoginRequestDTO loginRequest = new LoginRequestDTO();
        loginRequest.setName(username);
        loginRequest.setPassword(password);

        String response = mockMvc.perform(post("/api/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .content(asJsonString(loginRequest)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        LoginResponseDTO loginResponse = objectMapper.readValue(response, LoginResponseDTO.class);
        return loginResponse.getToken();
    }

    protected String loginAsAdmin() throws Exception {
        return login("Admin", "admin123");
    }
}
