package com.economato.inventory.domain.model;

public enum NotificationType {
    WEEKLY_PLAN_CREATED,
    WEEKLY_PLAN_ACTIVATED,
    WEEKLY_PLAN_SLOT_CONFIRMED,
    WEEKLY_PLAN_DAY_CONFIRMED,
    WEEKLY_PLAN_COMPLETED,
    WEEKLY_PLAN_CANCELLED,
    FOOD_CRISIS_ACTIVATED,
    FOOD_CRISIS_LIFTED,
    STOCK_PREDICTION_TRIGGERED,
    MANUAL
}
