package com.economato.inventory.infrastructure.config.web;

public enum MessageKey {
    ERROR_USER_DELETE_LAST_ADMIN("error.user.delete.last.admin"),
    ERROR_USER_REQUIRE_CURRENT_PASSWORD("error.user.require.current.password"),
    ERROR_USER_INVALID_CURRENT_PASSWORD("error.user.invalid.current.password"),
    ERROR_USER_HIDE_LAST_ADMIN("error.user.hide.last.admin"),
    ERROR_USER_ADMIN_CANNOT_HAVE_TEACHER("error.user.admin.cannot.have.teacher"),
    ERROR_USER_TEACHER_MUST_BE_ADMIN("error.user.teacher.must.be.admin"),
    ERROR_USER_ONLY_ADMIN_HAS_STUDENTS("error.user.only.admin.has.students"),
    ERROR_USER_ALREADY_ELEVATED("error.user.already.elevated"),
    ERROR_USER_CANNOT_ESCALATE_ADMIN("error.user.cannot.escalate.admin"),
    ERROR_AUTH_USER_ALREADY_EXISTS("error.auth.user.already.exists"),
    ERROR_AUTH_INVALID_LOGOUT_TOKEN("error.auth.invalid.logout.token"),
    ERROR_AUTH_LOGOUT_TOKEN_REQUIRED("error.auth.logout.token.required"),
    ERROR_AUTH_UNAUTHORIZED("error.auth.unauthorized"),

    ERROR_PRODUCT_ALREADY_EXISTS("error.product.already.exists"),
    ERROR_PRODUCT_CODE_ALREADY_EXISTS("error.product.code.already.exists"),
    ERROR_PRODUCT_DELETE_HAS_MOVEMENTS("error.product.delete.has.movements"),
    ERROR_PRODUCT_DELETE_IN_RECIPE("error.product.delete.in.recipe"),
    ERROR_PRODUCT_INVALID_UNIT("error.product.invalid.unit"),
    ERROR_PRODUCT_SUPPLIER_NOT_FOUND("error.product.supplier.not.found"),

    ERROR_SUPPLIER_ALREADY_EXISTS("error.supplier.already.exists"),

    ERROR_RECIPE_NO_COMPONENTS("error.recipe.no.components"),
    ERROR_RECIPE_ID_NOT_PROVIDED("error.recipe.id.not.provided"),
    ERROR_RECIPE_ID_NULL("error.recipe.id.null"),

    ERROR_ORDER_NOT_FOUND("error.order.not.found"),
    ERROR_ORDER_PRODUCT_NOT_FOUND("error.order.product.not.found"),
    ERROR_ORDER_CANNOT_RECEIVE_LESS("error.order.cannot.receive.less"),
    ERROR_ORDER_INVALID_STATE("error.order.invalid.state"),

    ERROR_OPTIMISTIC_LOCK("error.optimistic.lock"),
    ERROR_PESSIMISTIC_LOCK("error.pessimistic.lock"),
    ERROR_INTERNAL_SERVER_ERROR("error.internal.server.error"),
    ERROR_AUTH_BAD_CREDENTIALS("error.auth.bad.credentials"),
    ERROR_AUTH_JWT_INVALID("error.auth.jwt.invalid"),
    ERROR_AUTH_JWT_MISSING("error.auth.jwt.missing"),

    ERROR_RESOURCE_NOT_FOUND("error.resource.not.found"),
    ERROR_USER_NOT_FOUND("error.user.not.found"),
    ERROR_PRODUCT_NOT_FOUND("error.product.not.found"),
    ERROR_RECIPE_NOT_FOUND("error.recipe.not.found"),
    ERROR_SUPPLIER_NOT_FOUND("error.supplier.not.found"),
    ERROR_SUPPLIER_DELETE_HAS_PRODUCTS("error.supplier.delete.has.products"),
    ERROR_ORDER_NOT_FOUND_GENERAL("error.order.not.found.general"),
    ERROR_RECIPE_STOCK_INSUFFICIENT("error.recipe.stock.insufficient"),
    ERROR_STOCK_HASH_CALCULATION("error.stock.hash.calculation"),
    ERROR_AUTH_USER_HIDDEN("error.auth.user.hidden"),
    ERROR_AUTH_USER_NOT_FOUND("error.auth.user.not.found"),
    ERROR_REPORT_CUSTOM_DATES_REQUIRED("error.report.custom.dates.required"),
    REPORT_PERIOD_ALL_TIME("report.period.all.time"),
    GENERAL_SYSTEM("general.system"),
    GENERAL_POWERED_BY("general.powered.by"),
    GENERAL_NO_DATA("general.no.data"),
    GENERAL_UNIT_ABBREVIATION("general.unit.abbreviation"),
    REPORT_KITCHEN_TITLE("report.kitchen.title"),
    REPORT_PERIOD_LABEL("report.period.label"),
    REPORT_SECTION_GENERAL_INFO("report.section.general.info"),
    REPORT_LABEL_SESSIONS("report.label.sessions"),
    REPORT_LABEL_PORTIONS("report.label.portions"),
    REPORT_LABEL_DISTINCT_RECIPES("report.label.distinct.recipes"),
    REPORT_LABEL_DISTINCT_PRODUCTS("report.label.distinct.products"),
    REPORT_LABEL_DISTINCT_USERS("report.label.distinct.users"),
    REPORT_LABEL_EMISSION_DATE("report.label.emission.date"),
    REPORT_SECTION_TOP_RECIPES("report.section.top.recipes"),
    REPORT_COLUMN_RECIPE("report.column.recipe"),
    REPORT_COLUMN_TIMES_COOKED("report.column.times.cooked"),
    REPORT_COLUMN_TOTAL_PORTIONS("report.column.total.portions"),
    REPORT_SECTION_TOP_USERS("report.section.top.users"),
    REPORT_COLUMN_USER("report.column.user"),
    REPORT_COLUMN_SESSIONS_COUNT("report.column.sessions.count"),
    REPORT_SECTION_CONSUMPTION_ANALYSIS("report.section.consumption.analysis"),
    REPORT_COLUMN_PRODUCT("report.column.product"),
    REPORT_COLUMN_QUANTITY_CONSUMED("report.column.quantity.consumed"),
    REPORT_COLUMN_ESTIMATED_COST("report.column.estimated.cost"),
    REPORT_LABEL_TOTAL_ESTIMATED_COST("report.label.total.estimated.cost"),
    ERROR_REPORT_KITCHEN_PDF_GENERATION("error.report.kitchen.pdf.generation"),
    REPORT_SECTION_PRESENTATION("report.section.presentation"),
    REPORT_SECTION_ELABORATION("report.section.elaboration"),
    REPORT_SECTION_INGREDIENTS("report.section.ingredients"),
    REPORT_LABEL_TOTAL_COST("report.label.total.cost"),
    REPORT_SECTION_ALLERGENS("report.section.allergens"),
    REPORT_MESSAGE_NO_ALLERGENS("report.message.no.allergens"),
    ERROR_REPORT_RECIPE_PDF_GENERATION("error.report.recipe.pdf.generation"),
    REPORT_ORDER_TITLE_PREFIX("report.order.title.prefix"),
    REPORT_SECTION_ORDER_INFO("report.section.order.info"),
    REPORT_LABEL_USER("report.label.user"),
    REPORT_LABEL_STATUS("report.label.status"),
    REPORT_LABEL_DATE("report.label.date"),
    REPORT_LABEL_PRODUCTS_COUNT("report.label.products.count"),
    REPORT_SECTION_PRODUCTS_TITLE_PREFIX("report.section.products.title.prefix"),
    REPORT_COLUMN_UNIT_PRICE("report.column.unit.price"),
    REPORT_LABEL_TOTAL_ORDER("report.label.total.order"),
    ERROR_REPORT_ORDER_PDF_GENERATION("error.report.order.pdf.generation"),
    STATUS_CREATED("status.created"),
    STATUS_PENDING("status.pending"),
    STATUS_REVIEW("status.review"),
    STATUS_CONFIRMED("status.confirmed"),
    STATUS_INCOMPLETE("status.incomplete"),
    STATUS_CANCELLED("status.cancelled"),
    REPORT_COLUMN_QUANTITY("report.column.quantity"),
    REPORT_COLUMN_SUBTOTAL("report.column.subtotal"),
    ERROR_LEDGER_NO_ENTRIES("error.ledger.no.entries"),
    REPORT_LEDGER_TITLE_PREFIX("report.ledger.title.prefix"),
    REPORT_SECTION_PRODUCT_INFO("report.section.product.info"),
    REPORT_LABEL_NAME("report.label.name"),
    REPORT_LABEL_CODE("report.label.code"),
    REPORT_LABEL_TYPE("report.label.type"),
    REPORT_LABEL_CURRENT_STOCK("report.label.current.stock"),
    REPORT_LABEL_UNIT_PRICE("report.label.unit.price"),
    REPORT_SECTION_TRANSACTIONS("report.section.transactions"),
    REPORT_COLUMN_RESULTING_STOCK("report.column.resulting.stock"),
    REPORT_COLUMN_DATETIME("report.column.datetime"),
    REPORT_COLUMN_DESCRIPTION_USER("report.column.description.user"),
    REPORT_COLUMN_VERIFICATION("report.column.verification"),
    REPORT_BY_PREFIX("report.by.prefix"),
    STATUS_CORRUPT("status.corrupt"),
    STATUS_OK("status.ok"),
    REPORT_SECTION_SIGNATURE("report.section.signature"),
    REPORT_LABEL_INTEGRITY_STATUS("report.label.integrity.status"),
    STATUS_INTEGRAL("status.integral"),
    REPORT_LABEL_CORRUPTED_TXS("report.label.corrupted.txs"),
    GENERAL_NONE("general.none"),
    REPORT_LABEL_CONTENT_HASH("report.label.content.hash"),
    REPORT_LABEL_GENERATED("report.label.generated"),
    REPORT_LABEL_LAST_HASH("report.label.last.hash"),
    REPORT_LEGAL_NOTICE("report.legal.notice"),
    REPORT_FOOTER_PAGE("report.footer.page"),
    REPORT_FOOTER_CONFIDENTIAL("report.footer.confidential"),
    ERROR_REPORT_LEDGER_PDF_GENERATION("error.report.ledger.pdf.generation"),
    EXCEL_SHEET_PRODUCTS("excel.sheet.products"),
    REPORT_COLUMN_ID("report.column.id"),
    REPORT_COLUMN_NAME("report.column.name"),
    REPORT_COLUMN_TYPE("report.column.type"),
    REPORT_COLUMN_UNIT("report.column.unit"),
    REPORT_COLUMN_BARCODE("report.column.barcode"),
    REPORT_COLUMN_STOCK_CURRENT("report.column.stock.current"),
    REPORT_COLUMN_STOCK_MINIMUM("report.column.stock.minimum"),
    REPORT_COLUMN_AVAILABILITY("report.column.availability"),
    REPORT_COLUMN_SUPPLIER("report.column.supplier"),
    ERROR_ORDER_CANNOT_RECEIVE_LESS_DETAIL("error.order.cannot.receive.less.detail"),
    LEDGER_DESCRIPTION_RECEPTION("ledger.description.reception"),
    ERROR_ORDER_DETAIL_UPDATED_NOT_FOUND("error.order.detail.updated.not.found"),
    LEDGER_DESCRIPTION_MANUAL_ADJUSTMENT("ledger.description.manual.adjustment"),
    LEDGER_DESCRIPTION_COOKING("ledger.description.cooking"),
    LEDGER_DESCRIPTION_INITIAL_STOCK("ledger.description.initial.stock"),
    ERROR_AUTH_TOKEN_REVOKE_FAILED("error.auth.token.revoke.failed"),
    ERROR_USER_FIRST_LOGIN_REACTIVATE_DENIED("error.user.first.login.reactivate.denied"),
    ERROR_USER_TEACHER_NOT_FOUND("error.user.teacher.not.found"),
    ERROR_BATCH_OPERATION_FAILED("error.batch.operation.failed"),
    LEDGER_INTEGRITY_NO_TRANSACTIONS("ledger.integrity.no.transactions"),
    LEDGER_INTEGRITY_PREVIOUS_HASH_MISMATCH("ledger.integrity.previous.hash.mismatch"),
    LEDGER_INTEGRITY_HASH_CORRUPT("ledger.integrity.hash.corrupt"),
    LEDGER_INTEGRITY_SEQUENCE_BROKEN("ledger.integrity.sequence.broken"),
    LEDGER_INTEGRITY_VALID("ledger.integrity.valid"),
    LEDGER_INTEGRITY_CORRUPTED("ledger.integrity.corrupted"),
    LEDGER_REPAIR_STATUS("ledger.repair.status"),
    LEDGER_REPAIR_NO_TRANSACTIONS("ledger.repair.no.transactions"),
    LEDGER_RESET_SUCCESS("ledger.reset.success"),
    ERROR_CONSUMPTION_INVALID_DATE_RANGE("error.consumption.invalid.date.range"),
    ERROR_CONSUMPTION_PRODUCT_NOT_FOUND("error.consumption.product.not.found"),
    ERROR_BATCH_EXPIRED("error.batch.expired"),
    ERROR_BATCH_INSUFFICIENT_STOCK("error.batch.insufficient.stock"),
    STOCK_ALERT_MESSAGE_EXPIRING("stock.alert.message.expiring"),
    REPORT_COLUMN_NEAREST_EXPIRATION("report.column.nearest.expiration"),

    // Traceability and Crisis
    CRISIS_ACTIVATION_TITLE("crisis.activation.title"),
    CRISIS_ACTIVATION_MESSAGE("crisis.activation.message"),
    CRISIS_LIFT_TITLE("crisis.lift.title"),
    CRISIS_LIFT_MESSAGE("crisis.lift.message"),
    CRISIS_REPORT_TITLE("crisis.report.title"),
    CRISIS_REPORT_SECTION_AFFECTED_ORDERS("crisis.report.section.affected.orders"),
    CRISIS_REPORT_SECTION_AFFECTED_COOKINGS("crisis.report.section.affected.cookings"),
    CRISIS_REPORT_SECTION_QUARANTINE_PRODUCTS("crisis.report.section.quarantine.products"),
    CRISIS_REPORT_SECTION_TRACEABILITY_CHAIN("crisis.report.section.traceability.chain"),
    LEDGER_DESCRIPTION_QUARANTINE("ledger.description.quarantine"),
    LEDGER_DESCRIPTION_QUARANTINE_LIFT("ledger.description.quarantine.lift"),
    TRACEABILITY_SUMMARY_FORWARD("traceability.summary.forward"),
    TRACEABILITY_SUMMARY_REVERSE("traceability.summary.reverse"),
    REPORT_LABEL_CRISIS_ID("report.label.crisis.id"),
    REPORT_LABEL_REASON("report.label.reason"),
    REPORT_COLUMN_LATEST_HASH("report.column.latest.hash"),

    // Batch & Reversion
    ERROR_BATCH_EXPIRATION_REQUIRED("error.batch.expiration.required"),
    ERROR_BATCH_EXPIRATION_PAST("error.batch.expiration.past"),
    ERROR_BATCH_EXPIRED_CANNOT_ADD_STOCK("error.batch.expired.cannot.add.stock"),
    ERROR_BATCH_EXPIRED_CANNOT_REVERT("error.batch.expired.cannot.revert"),
    ERROR_REVERSION_ALREADY_DONE("error.reversion.already.done"),
    ERROR_REVERSION_NO_BATCH_TRACEABILITY("error.reversion.no.batch.traceability"),
    ERROR_COOKING_ALREADY_REVERTED("error.cooking.already.reverted"),
    ERROR_BATCH_DEPLETED_CANNOT_UPDATE("error.batch.depleted.cannot.update");

    private final String key;

    MessageKey(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
}
